name: Daily Green Contribution

on:
  schedule:
    - cron: '30 3 * * *'   # Daily 9:00 AM IST (UTC+5:30)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make daily update
        run: |
          echo "Last updated on $(date)" > daily-log.txt

      - name: Commit changes
        run: |
          git config --global user.name "Ashish Kumar"
          git config --global user.email "ashish@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Daily automated contribution"
          git push
